#pragma once

// From glfw3.h
#define ENIGMA_MOUSE_BUTTON_1         0
#define ENIGMA_MOUSE_BUTTON_2         1
#define ENIGMA_MOUSE_BUTTON_3         2
#define ENIGMA_MOUSE_BUTTON_4         3
#define ENIGMA_MOUSE_BUTTON_5         4
#define ENIGMA_MOUSE_BUTTON_6         5
#define ENIGMA_MOUSE_BUTTON_7         6
#define ENIGMA_MOUSE_BUTTON_8         7
#define ENIGMA_MOUSE_BUTTON_LAST      ENIGMA_MOUSE_BUTTON_8
#define ENIGMA_MOUSE_BUTTON_LEFT      ENIGMA_MOUSE_BUTTON_1
#define ENIGMA_MOUSE_BUTTON_RIGHT     ENIGMA_MOUSE_BUTTON_2
#define ENIGMA_MOUSE_BUTTON_MIDDLE    ENIGMA_MOUSE_BUTTON_3